### ISSUE TITLE
Code refactoring for HashCode generation 

### ISSUE THREAD

**Issue by ypriverol** [mpc-bioinformatics/pia#139]
The current code uses HashCodeBuilder as a mechanism to create the HashCode and equals. This is not efficient because every time a comparison is performed then an Object needs to be created. 

@julianu

**Comment by ypriverol** [comment]
the following PR address this issue: https://github.com/mpc-bioinformatics/pia/pull/141

**Comment by julianu** [comment]
Thanks for the improvement!
