### ISSUE TITLE
Review the dependency of inspector-ms-graph

### ISSUE THREAD

**Issue by ypriverol** [mpc-bioinformatics/pia#140]
Hi @julianu 

I think we should discuss the dependency of inspector-mz-graph in PIA. This introduces a lot of redundant dependencies that are not needed. This part of PIA can be removed and move into a desktop component. In addition in add a lot of swing classes into a backend algorithm. 

What do you think?

**Comment by ypriverol** [comment]
the following PR address this issue: https://github.com/mpc-bioinformatics/pia/pull/141

**Comment by julianu** [comment]
The dependencies are removed and only in the KNIME version now.
