### ISSUE TITLE
Last version of PIA fails on idxML format export file

### ISSUE THREAD

**Issue by giangiacomoberetta1** [mpc-bioinformatics/pia#159]
Hi !

I am experiencing a problem with the PIA node as it fails when the exportation format idxML is selected.

With the other options it works fine. It is still nice when working on protein inference only, but it hampers its connection with other downstream nodes requiring idxML format.

Thanks in advance!

**Comment by julianu** [comment]
Hej,

Thanks for pointing this out. I will look into this as soon as possible.
Nevertheless, could you specify the build number of the PIA and OpenMS version you installed, including the date strings?

Thanks,
Julian

**Comment by giangiacomoberetta1** [comment]
Hi Julian!

Thank you for considering my issue!

The versions currently installed are:

OpenMS	 2.6.0.202009301213      de.openms.feature.feature.group
PIA           1.3.13.v202009091421   de.mpc.pia.feature.feature.group

Thanks!

G

**Comment by julianu** [comment]
Hej giangiacomo,

I just tested the tutorial quant workflow (https://hub.knime.com/julianu/spaces/PIA/latest/02-PIA_and_quant) and on my installation it works with OpenMS 2.6.0 and PIA 1.3.13 using the tutorial data (https://github.com/julianu/pia-tutorial/tree/master/data).

Could you please check, whether this works on your side?
And maybe provide me with a workflow and data where your error occurred?

Thanks,
Julian

**Comment by julianu** [comment]
Hej,

I managed to also create an error for the export from OpenMS 2.6.0 files and will try to fix this.

@giangiacomoberetta1 Could you still provide me with files from your side which fail, to double check them?

Thanks,
Julian

**Comment by giangiacomoberetta1** [comment]
Hi J!

Sorry for the delay in the reply! 

I have tested the tutorial workflow and files. In my installation PIA works fine when exportation format is set to "mztab" and "csv" format (exportation level: protein), otherwise it comes out with the error message:

ERROR PIA Analysis         0:567      Execute failed: ("NullPointerException"): null

When exportation level is set to "PSM" or "peptide", only idxml the format option gives the same error (mzIndentML works).

If you agree, I can send to you the workflow. Which is the most convenient way for you to receive it?

Thanks again!

G

**Comment by julianu** [comment]
Hej,

Most convenient would be if you could attach the workflow in a comment here.
Make sure to not reset the workflow on export in KNIME.

Best,
Julian

**Comment by giangiacomoberetta1** [comment]
OK! is it correct in this way ?


[02-PIA_and_quant_TEST_combination.zip](https://github.com/mpc-bioinformatics/pia/files/5526002/02-PIA_and_quant_TEST_combination.zip)

**Comment by julianu** [comment]
Hej @giangiacomoberetta1 ,

I see you added some additional identification nodes to the basic tutorial workflow, great.
For the purpose of debugging your exact problem (with your data) could you run the workflow up until the PIA node which has the error and then export the workflow? In your case, the first zipLoop, containing the identification and also the FeatureFinderIdentification, would be great to execute, because you used some databases I don't have around.

If the workflow containing this data is to big to upload here, write me a mail (see my profile) and I will give you another way to send me the data.

Best,
Julian

**Comment by giangiacomoberetta1** [comment]
Hi @julianu !

Thank you as always! I just need an advice. Which option should I use to export the complete workflow ?

Is "Export KNIME workflow" option producing the suitable files?

 best greetings,

G

**Comment by julianu** [comment]
Yes, this export option should work.
Only make sure to not select the "Reset workflow(s) before export".

**Comment by giangiacomoberetta1** [comment]
Great! Thank you for the instruction.

The final file is almost 500 Gb big, so cannot be uploaded here.

How to do it?!

Thanks!

G

**Comment by julianu** [comment]
@giangiacomoberetta1 please contact me at julian.uszkoreit [at] rub.de to share the file.

**Comment by giangiacomoberetta1** [comment]
Hi @julianu,

yes sure. Just I am unsure how to apply the update? Can I do it through a KNIME option?

**Comment by giangiacomoberetta1** [comment]
@julianu I see an update option available now for PIA in KNIME

**Comment by giangiacomoberetta1** [comment]
Test done, it's working greatly!

**Comment by julianu** [comment]
Perfect, then I will close this issue.
