### ISSUE TITLE
how to export PIA analysis results ?

### ISSUE THREAD

**Issue by olangella** [mpc-bioinformatics/pia#40]
Hello,

I continue my self training using PIA in Knime.
Thanks you help that helped me a lot.

Now, I have a simple workflow from mzid files, to PIA compiler and PIA analysis.

I would like to export the result of the grouping algorithm to something like TSV, XLS or other table format.

I've tried to connect the 3 output link to XLS Writer or XLS sheet appender : 
This gives me 3 tables, but I don't find Protein Accessions, protein groups and protein clusters.

The last output is clearly marked as unimplemented. I've tried but this gave me no results (mzTab, csv, mzIdentML).

So I'me wondering how to get some table... Is there some other node to use ?
perhaps using the embeded view ?
Is it possible with other tools, with CLI or the web interface ?

Cheers
Olivier

**Comment by julianu** [comment]
Hej Olivier,

Even though the last output port is still labelled as not implemented, it is working for idXML (OpenMS's format) right now. But, if you really want to get the most out of it (clusters, groups and sub-groups etc.), I would recommend you use the mzIdentML export. Support for this I will upload in a couple of days (it's working here already).

The much simpler CSV-export will also be working in a couple of days, I am just cleaning up the code a bit, and this will probably also allow sub-group export.

Just writing this, I realised, that your problem actually might lie with the XLS writer:
If you just have a look at the protein table from the PIA node (right click on node, "2: protein results"), you will see additionally to your export accessions and coverages. These, though, are internally lists in KNIME and cannot be exported by the XLS writer.
To fix this, attach a "Column rename" node to the desired table and change the Type of the lists (the ones with "(...)" as type on the left in the rename dialog) to String. This should export just fine.
The reason behind this is, that PIA always creates protein  groups , though some may have only one accession.

Cheers,
Julian

**Comment by olangella** [comment]
Thanks for the quick reply,

Yes I can see the hidden lists of accessions. So, if I understand well, each "protein list" defines a group ? There is no problem for me to consider one protein as a group.
If yes, I can get the group informations.
But how can I retrieve clusters ?
Do you think it would be possible to just add some cluster identifiers and groups identifiers in the table ?

Perhaps that I can get clusters and groups informations using an OpenMS node that would take as input the IdXML ?

Thaks for your advices
Cheers
Olivier

**Comment by julianu** [comment]
Each entry/row in the protein list is a group, right.
Actually, adding the cluster information can be accomplished easily, yes. I will try to add this in the next update.
IdXML does not really have the concept of clusters, as far as I know.

Just to explain the concept of clusters in PIA, so you are not disappointed if it is not, what you wanted: proteins/peptides/PSMs are in the same cluster, if they are in the same intermediate structure, i.e. there is any connection of shared peptides between them. A cluster here does NOT mean any genomic or protein class relationship, which is also sometimes used.

**Comment by olangella** [comment]
Sorry to bother you again,
I've tried the IdXML output, it doesn't complains, but I don't find the corresponding file in my local "PIA analysis" filestore.
I've tried IdXML with the PSM and protein export level.

Perhaps that my PIA analysis node is too old or I don't use it correctly ?

Cheers
Olivier

**Comment by olangella** [comment]
Yes exactly, the concept of cluster is for me some groups of proteins that share at least one PSM or one peptide.
Thanks for the explanation on groups.
Yes, I would badly need some informations on clusters ;-)
We find this very interesting in our facility.
So I will wait for an update...

Thanks for your help and time
Cheers
Olivier

**Comment by julianu** [comment]
Please try the "Output File" (or "Output Folder") with the last port. This will write the file to the desired position. If an export level and file format is selected and the node does not give any error or warning, it should export the data.

**Comment by olangella** [comment]
Thanks again, I've found it and the content is OK.
The default location was in my temporary directory and not in the knime workspace.
But there is no hope to find cluster information in the IdXML output I guess :(

I stay tuned for an update :)
Cheers
Olivier

**Comment by julianu** [comment]
Hej Olivier,

If you upgrade the PIA nodes now, you should also get a "clusterID" column in the proteins results. This is an internal integer, but all protein groups with the same ID are in the same PIA intermediate structure, i.e. they have based on the identified peptides given to the PIA compiler a connection between their PSMs/peptides/accessions.

Cheers,
Julian

**Comment by olangella** [comment]
Thanks for this super fast upgrade. I will test it asap.

Cheers,
Olivier

**Comment by julianu** [comment]
Hej Olivier,
Did the export work for you now?

Cheers,
Julian

**Comment by olangella** [comment]
Hello Julian,

sorry for the late response, I've forgotten to give some news.
Yes it's Ok. I've the ClusterId column and complete tables using the column rename Knime module.

Thanks for your help,
Olivier
